name: 'Docker Build and Push'
description: 'Builds and pushes a Docker image to Docker Hub'

inputs:
  docker-hub-account:
    description: 'Docker Hub username'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-version:
    description: 'Docker image version/tag'
    required: false
    default: 'latest'
  project-path:
    description: 'Path to the Dockerfile'
    required: true
  docker-username:
    description: 'Docker Hub login username'
    required: true
  docker-password:
    description: 'Docker Hub login password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.docker-hub-account }}/${{ inputs.image-name }}:${{ inputs.image-version }} ${{ inputs.project-path }}
      shell: bash

    - name: Push Docker image
      run: |
        docker push ${{ inputs.docker-hub-account }}/${{ inputs.image-name }}:${{ inputs.image-version }}
      shell: bash
