name: 'Auto-increment Git tag'
description: 'Finds the latest Git tag, increments patch, and creates a new tag'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest tag and bump
      id: bump
      shell: bash
      run: |
        git fetch --tags

        LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
        echo "Last tag: $LAST_TAG"

        VERSION=$(echo "$LAST_TAG" | sed 's/^v//')
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

        if [[ -z "$MAJOR" || -z "$MINOR" || -z "$PATCH" ]]; then
          MAJOR=0
          MINOR=0
          PATCH=0
        fi

        PATCH=$((PATCH + 1))
        NEW_TAG="v$MAJOR.$MINOR.$PATCH"

        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        echo "New tag will be: $NEW_TAG"

    - name: Create and push tag
      shell: bash
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git tag -a $NEW_TAG -m "Release $NEW_TAG"
        git push origin $NEW_TAG
