name: 'Show .NET Version'

description: 'Simple action that shows the .NET SDK version'

inputs:
  project-name:
    description: 'The .NET project to work with'
    required: true
  dotnet-version:
    description: 'The .NET version to install'
    required: false
    default: '9.0.x'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Show .NET version
      run: dotnet --version
      shell: bash

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project-name }}
      shell: bash

    - name: Build project
      run: dotnet build ${{ inputs.project-name }} --no-restore
      shell: bash

    - name: Run Tests
      run: dotnet test ${{ inputs.project-name }} --no-build --verbosity normal
      shell: bash
