apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    # environment: test # test, dev, val, prod
    app: hello-minikube
  annotations:
    description: "Namespace for the argocd application"

---

apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    # environment: test # test, dev, val, prod
    app: hello-minikube
  annotations:
    description: "Namespace for the test application"

---

apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    # environment: dev # test, dev, val, prod
    app: hello-minikube
  annotations:
    description: "Namespace for the development application"

---

apiVersion: v1
kind: Namespace
metadata:
  name: val
  labels:
    # environment: val # test, dev, val, prod
    app: hello-minikube
  annotations:
    description: "Namespace for the validation application"

---

apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    # environment: prod # test, dev, val, prod
    app: hello-minikube
  annotations:
    description: "Namespace for the production application"