name: Stop AWS EC2 Instances

on:
  schedule:
    - cron: '0 22 * * *' # Every day at 22:00 UTC
  workflow_dispatch:

jobs:
  stop-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: VKalenski/GitHub-Actions-Templates/.github/actions/aws-configure@main
        with:
          region: 'eu-west-3'

      - name: Stop all running EC2 instances
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)

          if [ -n "$INSTANCE_IDS" ]; then
            echo "Stopping EC2 instances: $INSTANCE_IDS"
            aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          else
            echo "No running EC2 instances to stop."
          fi
