name: Build and Test .NET

on:
  workflow_call:
    inputs:
      project-name:
        description: 'The .NET project to work with'
        required: true
        type: string
      dotnet-version:
        required: false
        type: string
        default: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: ./.github/actions/dotnet-version@main
        with:
          project-name: ${{ inputs.project-name }}
          dotnet-version: ${{ inputs.dotnet-version }}
