name: Install Tools on Ubuntu

on:
  workflow_dispatch:
    inputs:
      mssql-password:
        description: 'Password for MSSQL'
        required: true
        type: string
        default: '12345'

jobs:
  install-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packages
        run: |
          echo "RUN APT UPDATE"
          sudo apt update
          echo

      - name: Upgrade Packages
        run: |
          echo "RUN APT UPGRADE"
          sudo apt upgrade -y
          echo

      - name: Install wget
        run: |
          echo "RUN APT INSTALL WGET"
          sudo apt install wget -y
          wget --version
          echo

      - name: Install curl
        run: |
          echo "INSTALLATION 'curl'"
          sudo apt install curl -y
          curl --version
          echo

      - name: Install unzip
        run: |
          echo "INSTALLATION 'unzip'"
          sudo apt install unzip -y
          unzip --version
          echo

      - name: Install netstat
        run: |
          echo "INSTALLATION 'netstat'"
          sudo apt install net-tools -y
          netstat --version
          echo

      - name: Install xvfb
        run: |
          echo "INSTALLATION 'xvfb'"
          sudo apt install xvfb -y
          Xvfb --version
          echo

      - name: Install .NET 8.0 SDK
        run: |
          echo "INSTALLATION '.NET 8.0 SDK'"
          sudo apt install -y wget apt-transport-https
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt install -y dotnet-sdk-8.0
          dotnet --version
          rm *.deb
          echo "Installation completed and temporary files deleted."
          echo

      - name: Download Google Chrome
        run: |
          echo "DOWNLOAD 'Google Chrome'"
          wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/google-chrome-stable_current_amd64.deb
          echo

      - name: Install Google Chrome
        run: |
          echo "INSTALLATION 'Google Chrome'"
          sudo apt install -y /tmp/google-chrome-stable_current_amd64.deb
          google-chrome --version
          echo

      - name: Install Docker
        run: |
          echo "INSTALLATION 'Docker'"
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt install -y docker-ce
          sudo systemctl status docker
          # sudo usermod -aG docker ${USER}
          sudo usermod -aG docker $(whoami)
          echo

      - name: Pull MSSQL image and start the container
        env:
          SA_PASSWORD: ${{ inputs.mssql-password }}
        run: |
          echo "Pull MSSQL image and start the container"
          docker pull mcr.microsoft.com/mssql/server:2022-latest
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=SA_PASSWORD" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest
          docker update --restart=always sql1
          echo
